version: "3.9"
services:
  radikron:
    build: .
    image: ghcr.io/iomz/radikron:latest
    container_name: radikron
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./config.yml:/app/config.yml
      - ./radiko:/radiko
